<?php
    use GRAM\MVPGram;
    use JetPHP\Model\Start;
    $mvpgram = new MVPGram();
    $idPosts = $dadosUsuario->posts;
    $idPostsString = trim($idPosts, "()");
    if(empty($idPostsString)){
        $qtdPosts = 0;
    }else{
        $idPosts = explode(',', $idPosts);
        $qtdPosts = count($idPosts);
    }
    $posts = $mvpgram->getPostsByUsername($dadosUsuario->username);
    $dadosUsuarioAtivo = $mvpgram->getDadosUserByUsername(Start::session('username')); 
    $qtdFollowers = $mvpgram->getQtdFollowersByUsername($dadosUsuario->username);
    $qtdFollowing = $mvpgram->getQtdFollowingByUsername($dadosUsuario->username);
?>

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sdrow</title>
    <link rel="shortcut icon" href="../misc/imagens/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="../misc/css/bottombar.css">
    <link rel="stylesheet" href="../misc/css/sidebar.css">
    <link rel="stylesheet" href="../misc/css/perfil.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"/>
    <script src="https://kit.fontawesome.com/8715f0f9da.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
    <div class="sidebar">
        <div class="siderbar-side-top">
            <div class="sidebar-top">
                <div class="logo">
                    <img src="../misc/imagens/logos/icone.png" alt="">
                    <span>Sdrow</span>
                </div>
            </div>
            <div class="sidebar-user">
                <div class="sidebar-user-img">
                    <img src="<?=($dadosUsuarioAtivo->foto == '') ? '../misc/imagens/semFoto.png' : $dadosUsuarioAtivo->foto?>" alt="Imagem Usuário" class="user-img">
                    <a href="/perfil/<?=$dadosUsuarioAtivo->username?>" class = "user-behind-perfil">
                        <span class="bold">Perfil</span>
                    </a>
                </div> 
                <div>
                    <p class="bold user-title"><?=ucfirst(strtolower($dadosUsuarioAtivo->nome))?></p>
                    <p class="user-username">@<?=$dadosUsuarioAtivo->username?></p>
                </div>
            </div>
                      
            <ul class="sidebar-list">
                <li>
                    <a href="/" class="home">
                        <i class="material-symbols-outlined">home</i>
                        <span class="nav-item">Início</span>
                    </a>
                    <span class="tooltip">Início</span>
                </li>
                <li>
                    <a href="sdrow/feed.html" class="premium">
                        <i class="material-symbols-outlined">token</i>
                        <span class="nav-item" id="plano">Premium</span>
                    </a>
                    <span class="tooltip">Premium</span>
                </li>
                <li>
                    <a href="#" class="mensagens">
                        <i class="material-symbols-outlined">mail</i>
                        <span class="nav-item">Mensagens</span>
                    </a>
                    <span class="tooltip">Mensagens</span>
                </li>
                <li>
                    <a href="../notificacoes" class="notificacoes">
                        <i class="material-symbols-outlined">notifications</i>
                        <span class="nav-item">Notificações</span>
                    </a>
                    <span class="tooltip">Notificações</span>
                </li>
                <li>
                    <a href="../configuracoes" class="configuracoes">
                        <i class="material-symbols-outlined">settings</i>
                        <span class="nav-item">Configurações</span>
                    </a>
                    <span class="tooltip">Configurações</span>
                </li>
                <li class="list-publicar" style="display: none;">
                    <a href="publica/">
                        <i class="material-symbols-outlined">send</i>
                        <span class="nav-item">Publicar</span>
                    </a>
                    <span class="tooltip">Publicar</span>
                </li>
            </ul>
        </div>
        <div class="sidebar-side-bottom">
            <ul class="sidebar-list">
                <li class="list-publicar">
                    <a href="#" class="btnLogout">
                        <i class="material-symbols-outlined">logout</i>
                        <span class="nav-item">Sair</span>
                    </a>
                    <span class="tooltip">Sair</span>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-content">
        <div class="container">   
            <p style="color: white;">
            </p>
            <div class="box-top-perfil">
                <div class="box-perfil-img">
                    <img src="<?=($dadosUsuario->foto == '') ? '../misc/imagens/semFoto.png' : $dadosUsuario->foto?>" alt="Imagem Usuário" class="user-img-perfil">
                </div>
                <div class="box-perfil-info">
                    <div class="perfil-username bold">
                        <p><?=$dadosUsuario->username?></p>
                        <?php
                            if($dadosUsuario->username==Start::session("username")){
                        ?>
                                <a href="../configuracoes"><button class="btnEditarPerfil bold">Editar Perfil</button></a>
                        <?php
                            }else{
                                if($mvpgram->checkfollow($dadosUsuario->username)){
                                    $txt = 'Deixar de seguir';
                                }else{
                                    $txt = 'Seguir';
                                }
                        ?>
                                <button data-username="<?=$dadosUsuario->username?>" class="btn btnFollowUser bold"><?=$txt?></button>
                        <?php
                            }
                        ?>
                        
                    </div>
                    <div class="perfil-dados">
                        <p><?=$qtdPosts?> publicação</p>
                        <p class="followers"><?=$qtdFollowers?> seguidores</p>
                        <p><?=$qtdFollowing?> seguindo</p>
                    </div>
                    <div class="perfil-biografia">
                        <p><?=nl2br($dadosUsuario->biografia)?></p>
                    </div>
                </div>
            </div>
            <div class="box-bottom-posts">
                <hr>
                <div class="bottom-options bold">
                    <div class="option optionPosts" data-username="<?=$dadosUsuario->username?>">
                        <i class="material-symbols-outlined">apps</i>
                        <p>Posts</p>
                    </div>
                    <div class="option optionCurtidos" data-username="<?=$dadosUsuario->username?>">
                        <i class="material-symbols-outlined">favorite</i>
                        <p>Curtidos</p>
                    </div>
                </div>
                <div class="group-post">
                    <?php
                        if($posts!=false){
                            foreach($posts as $post){
                    ?>
                                <div class="post card-post-img" data-img="<?=$post->imagem?>" data-idPost="<?=$post->id?>"></div>
                    <?php
                            }
                    ?> 
                </div>
                    <?php
                        }else{
                    ?>
                        <div class="noPost">
                                <i class="material-symbols-outlined">photo_camera</i>
                                <p class="bold">Nenhuma Publicação</p>
                            </div>
                    <?php
                        }
                    ?>
                
                <div class="box-end"></div>
            </div>
        </div>


        

        <nav class="bottombar">
            <ul class="bottombar-list">
                <li><a href="/"><i class="material-symbols-outlined icon home">home</i></a></li>
                <li><a href="sdrow/mensagens.html"><i class="material-symbols-outlined icon mail">mail</i></a></li>
                <li><a href="#"><i class="material-symbols-outlined icon token">token</i></a></li>
                <li><a href="notificacoes"><i class="material-symbols-outlined icon notifications">notifications</i></a></li>
                <li><a href="../configuracoes"><i class="material-symbols-outlined icon settings">settings</i></a></li>
            </ul>
        </nav>
    </div>
    
    <script src="../misc/js/bottombar.js"></script>
    <script src="../misc/js/ajaxMVP.js"></script>
</body>
    
</html> 